Repository michael-gokey-architect/connections.biotool.me, pull requests merged in 2024-06, with the labels that each got.

#4 S6 mg framework
  connections/README.md
  connections/src/app/app-routing.module.ts
  connections/src/app/app.component.html
  connections/src/app/app.component.ts
  connections/src/app/core/models/connection.interface.ts
  connections/src/app/core/models/event.interface.ts
  connections/src/app/core/models/organization.interface.ts
  connections/src/app/core/models/quest.interface.ts
  connections/src/app/core/models/user.interface.ts
  connections/src/app/core/services/connection.service.spec.ts
  connections/src/app/core/services/data-connect-mg.service.spec.ts
  connections/src/app/core/services/data-connect-mg.service.ts
  connections/src/app/core/services/event.service.spec.ts
  connections/src/app/core/services/organization.service.spec.ts
  connections/src/app/core/services/organization.service.ts
  connections/src/app/core/services/quest.service.spec.ts
  connections/src/app/core/services/user.service.spec.ts
  connections/src/app/features-michael/com-one/com-one.component.css
  connections/src/app/features-michael/com-one/com-one.component.html
  connections/src/app/features-michael/com-one/com-one.component.spec.ts
  connections/src/app/features-michael/com-one/com-one.component.ts
  connections/src/app/features-michael/com-two/com-two.component.css
  connections/src/app/features-michael/com-two/com-two.component.html
  connections/src/app/features-michael/com-two/com-two.component.spec.ts
  connections/src/app/features-michael/com-two/com-two.component.ts
  connections/src/app/features-michael/features-michael.module.ts
  connections/src/app/features/features.module.ts
  connections/src/app/features/manage-alias/manage-alias.component.css
  connections/src/app/features/manage-alias/manage-alias.component.html
  connections/src/app/features/manage-alias/manage-alias.component.spec.ts
  connections/src/app/features/manage-alias/manage-alias.component.ts
  connections/src/app/features/page-blue/page-blue.component.css
  connections/src/app/features/page-blue/page-blue.component.html
  connections/src/app/features/page-blue/page-blue.component.spec.ts
  connections/src/app/features/page-blue/page-blue.component.ts
  connections/src/app/features/page-purple/page-purple.component.css
  connections/src/app/features/page-purple/page-purple.component.html
  connections/src/app/features/page-purple/page-purple.component.spec.ts
  connections/src/app/features/page-purple/page-purple.component.ts
  connections/src/app/features/page-red/page-red.component.css
  connections/src/app/features/page-red/page-red.component.html
  connections/src/app/features/page-red/page-red.component.spec.ts
  connections/src/app/features/page-red/page-red.component.ts
  connections/src/app/features/theme-switcher/theme-switcher.component.css
  connections/src/app/features/theme-switcher/theme-switcher.component.html
  connections/src/app/features/theme-switcher/theme-switcher.component.spec.ts
  connections/src/app/features/theme-switcher/theme-switcher.component.ts
  connections/src/app/organization/organization-landing/organization-landing.component.css
  connections/src/app/organization/organization-landing/organization-landing.component.html
  connections/src/app/organization/organization-landing/organization-landing.component.spec.ts
  connections/src/app/organization/organization-landing/organization-landing.component.ts
  connections/src/app/organization/organization.module.ts
  connections/src/environments/environment.dev.ts
  connections/src/environments/environment.prod.ts
  connections/src/environments/environment.staging.ts
Labels: enhancement

#5 S6 mg framework
  connections/README.md
  connections/src/app/app-routing.module.ts
  connections/src/app/features/features.module.ts
  connections/src/app/features/page-gray/page-gray.component.css
  connections/src/app/features/page-gray/page-gray.component.html
  connections/src/app/features/page-gray/page-gray.component.spec.ts
  connections/src/app/features/page-gray/page-gray.component.ts
  connections/src/app/shared/layout/header/header.component.html
Labels: enhancement

#6 S5 er perfect blue
  connections/angular.json
  connections/package-lock.json
  connections/package.json
  connections/src/app/app-routing.module.ts
  connections/src/app/features-epris/features-epris.module.ts
  connections/src/app/features-epris/page-blue/page-blue.component.css
  connections/src/app/features-epris/page-blue/page-blue.component.html
  connections/src/app/features-epris/page-blue/page-blue.component.spec.ts
  connections/src/app/features-epris/page-blue/page-blue.component.ts
  connections/src/app/features-epris/page-gray/page-gray.component.css
  connections/src/app/features-epris/page-gray/page-gray.component.html
  connections/src/app/features-epris/page-gray/page-gray.component.spec.ts
  connections/src/app/features-epris/page-gray/page-gray.component.ts
  connections/src/app/features-epris/page-purple/page-purple.component.css
  connections/src/app/features-epris/page-purple/page-purple.component.html
  connections/src/app/features-epris/page-purple/page-purple.component.spec.ts
  connections/src/app/features-epris/page-purple/page-purple.component.ts
  connections/src/app/features-epris/page-red/page-red.component.css
  connections/src/app/features-epris/page-red/page-red.component.html
  connections/src/app/features-epris/page-red/page-red.component.spec.ts
  connections/src/app/features-epris/page-red/page-red.component.ts
  connections/src/app/features/theme-switcher/theme-switcher.component.css
  connections/src/app/shared/layout/header/header.component.html
  connections/src/assets/icon/hamburger.png
  connections/src/index.html
  connections/src/styles.css
  connections/tailwind.config.js
  package-lock.json
Labels: enhancement, help wanted

#7 S5 er perfect blue
  connections/src/app/features-epris/page-blue/page-blue.component.css
  connections/src/app/features-epris/page-blue/page-blue.component.html
  connections/src/app/features-epris/page-blue/page-blue.component.ts
  connections/src/app/features-epris/page-gray/page-gray.component.css
  connections/src/app/features-epris/page-gray/page-gray.component.html
  connections/src/app/features-epris/page-purple/page-purple.component.css
  connections/src/app/features-epris/page-purple/page-purple.component.html
  connections/src/app/features-epris/page-purple/page-purple.component.ts
  connections/src/app/features-epris/page-red/page-red.component.css
  connections/src/app/features-epris/page-red/page-red.component.html
  connections/src/app/features-epris/page-red/page-red.component.ts
  connections/src/app/shared/layout/header/header.component.html
  connections/src/assets/images/onboarding-images/pw-background.jpg
  connections/src/styles.css
  connections/src/theme-switcher-fonts.rtf
  connections/tailwind.config.js
Labels: enhancement

#11 read me notes
  connections/README.md
Labels: enhancement

#12 Environment configuration
  connections/angular.json
  connections/package.json
  connections/src/app/app.component.html
  connections/src/app/app.component.ts
  connections/src/environments/environment.testing.ts
  connections/src/environments/environment.ts
Labels: enhancement

#16 Roles and Tags CRUD
  connections/package-lock.json
  connections/src/app/app-routing.module.ts
  connections/src/app/core/models/pii.interface.ts
  connections/src/app/core/models/pii.ts
  connections/src/app/core/models/roles.interface.ts
  connections/src/app/core/models/roles.ts
  connections/src/app/core/models/tags.interface.ts
  connections/src/app/core/models/tags.ts
  connections/src/app/core/services/pii.service.ts
  connections/src/app/core/services/roles.service.ts
  connections/src/app/core/services/tags.service.ts
  connections/src/app/shared/pii/create-pii/create-pii.component.html
  connections/src/app/shared/pii/create-pii/create-pii.component.ts
  connections/src/app/shared/pii/get-pii/get-pii.component.ts
  connections/src/app/shared/pii/pii-landing/pii-landing.component.ts
  connections/src/app/shared/roles/create-roles/create-roles.component.html
  connections/src/app/shared/roles/create-roles/create-roles.component.ts
  connections/src/app/shared/roles/delete-roles/delete-roles.component.html
  connections/src/app/shared/roles/delete-roles/delete-roles.component.ts
  connections/src/app/shared/roles/get-roles/get-roles.component.html
  connections/src/app/shared/roles/get-roles/get-roles.component.ts
  connections/src/app/shared/roles/role-landing/role-landing.component.html
  connections/src/app/shared/roles/role-landing/role-landing.component.ts
  connections/src/app/shared/roles/update-roles/update-roles.component.html
  connections/src/app/shared/roles/update-roles/update-roles.component.ts
  connections/src/app/shared/shared.module.ts
  connections/src/app/shared/tags/create-tags/create-tags.component.html
  connections/src/app/shared/tags/create-tags/create-tags.component.ts
  connections/src/app/shared/tags/delete-tags/delete-tags.component.html
  connections/src/app/shared/tags/delete-tags/delete-tags.component.ts
  connections/src/app/shared/tags/get-tags/get-tags.component.html
  connections/src/app/shared/tags/get-tags/get-tags.component.ts
  connections/src/app/shared/tags/tag-landing/tag-landing.component.html
  connections/src/app/shared/tags/tag-landing/tag-landing.component.ts
  connections/src/app/shared/tags/update-tags/update-tags.component.html
  connections/src/app/shared/tags/update-tags/update-tags.component.ts
Labels: enhancement, WIP

#14 S 7 sid piiandlinks slight modification
  connections/src/app/shared/links/delete-links/delete-links.component.html
  connections/src/app/shared/links/delete-links/delete-links.component.ts
  connections/src/app/shared/links/get-links/get-links.component.html
  connections/src/app/shared/links/update-links/update-links.component.html
  connections/src/app/shared/links/update-links/update-links.component.ts
  connections/src/app/shared/pii/update-pii/update-pii.component.ts
Labels: don't merge, WIP

#19 jest configuration and fixes in all test cases
  connections/jest.config.js
  connections/package-lock.json
  connections/package.json
  connections/setup-jest.ts
  connections/src/app/app.component.spec.ts
  connections/src/app/core/services/links.service.spec.ts
  connections/src/app/core/services/organization.service.spec.ts
  connections/src/app/core/services/pii.service.spec.ts
  connections/src/app/core/services/roles.service.spec.ts
  connections/src/app/core/services/tags.service.spec.ts
  connections/src/app/organization/create-organization/create-organization.component.spec.ts
  connections/src/app/organization/delete-organization/delete-organization.component.spec.ts
  connections/src/app/organization/get-organization/get-organization.component.spec.ts
  connections/src/app/organization/update-organization/update-organization.component.spec.ts
  connections/src/app/shared/links/create-links/create-links.component.spec.ts
  connections/src/app/shared/links/delete-links/delete-links.component.spec.ts
  connections/src/app/shared/links/get-links/get-links.component.spec.ts
  connections/src/app/shared/links/update-links/update-links.component.spec.ts
  connections/src/app/shared/pii/create-pii/create-pii.component.spec.ts
  connections/src/app/shared/pii/delete-pii/delete-pii.component.spec.ts
  connections/src/app/shared/pii/get-pii/get-pii.component.spec.ts
  connections/src/app/shared/pii/update-pii/update-pii.component.spec.ts
  connections/src/app/shared/roles/create-roles/create-roles.component.spec.ts
  connections/src/app/shared/roles/delete-roles/delete-roles.component.spec.ts
  connections/src/app/shared/roles/get-roles/get-roles.component.spec.ts
  connections/src/app/shared/roles/update-roles/update-roles.component.spec.ts
  connections/src/app/shared/tags/create-tags/create-tags.component.spec.ts
  connections/src/app/shared/tags/delete-tags/delete-tags.component.spec.ts
  connections/src/app/shared/tags/get-tags/get-tags.component.spec.ts
  connections/src/app/shared/tags/update-tags/update-tags.component.spec.ts
  connections/tsconfig.json
  connections/tsconfig.spec.json
Labels: enhancement

#21 shifting env variable to connection service
  connections/src/app/app.component.html
  connections/src/app/app.component.ts
  connections/src/app/core/services/connection.service.ts
  connections/src/app/features/crud/crud.component.html
  connections/src/app/features/crud/crud.component.ts
Labels: enhancement

#20 s7-sid-package lock file added in gitignore
  connections/.gitignore
  connections/package-lock.json
Labels: enhancement
