Repository michael-gokey-architect/connections.biotool.me, pull requests merged in 2024-07, with the labels that each got.

#18 Events and Connections CRUD
  connections/src/app/app-routing.module.ts
  connections/src/app/app.module.ts
  connections/src/app/connections/connection-central/connection-central.component.html
  connections/src/app/connections/connection-central/connection-central.component.ts
  connections/src/app/connections/connections.module.ts
  connections/src/app/connections/create-connections/create-connections.component.html
  connections/src/app/connections/create-connections/create-connections.component.ts
  connections/src/app/connections/delete-connections/delete-connections.component.css
  connections/src/app/connections/delete-connections/delete-connections.component.html
  connections/src/app/connections/delete-connections/delete-connections.component.spec.ts
  connections/src/app/connections/delete-connections/delete-connections.component.ts
  connections/src/app/connections/get-connections/get-connections.component.html
  connections/src/app/connections/get-connections/get-connections.component.ts
  connections/src/app/connections/update-connections/update-connections.component.html
  connections/src/app/connections/update-connections/update-connections.component.ts
  connections/src/app/core/models/event.interface.ts
  connections/src/app/core/services/connection.service.ts
  connections/src/app/core/services/event.service.ts
  connections/src/app/events/create-events/create-events.component.css
  connections/src/app/events/create-events/create-events.component.html
  connections/src/app/events/create-events/create-events.component.spec.ts
  connections/src/app/events/create-events/create-events.component.ts
  connections/src/app/events/delete-events/delete-events.component.css
  connections/src/app/events/delete-events/delete-events.component.html
  connections/src/app/events/delete-events/delete-events.component.spec.ts
  connections/src/app/events/delete-events/delete-events.component.ts
  connections/src/app/events/events-landing/events-landing.component.html
  connections/src/app/events/events-landing/events-landing.component.ts
  connections/src/app/events/events.module.ts
  connections/src/app/events/get-events/get-events.component.css
  connections/src/app/events/get-events/get-events.component.html
  connections/src/app/events/get-events/get-events.component.spec.ts
  connections/src/app/events/get-events/get-events.component.ts
  connections/src/app/events/update-events/update-events.component.css
  connections/src/app/events/update-events/update-events.component.html
  connections/src/app/events/update-events/update-events.component.spec.ts
  connections/src/app/events/update-events/update-events.component.ts
Labels: enhancement

#24 Qr code scanner ngx qrcode2
  .gitignore
  connections/README.md
  connections/package.json
  connections/src/app/app-routing.module.ts
  connections/src/app/app.module.ts
  connections/src/app/core/core.module.ts
  connections/src/app/core/services/qr-code-generator.service.spec.ts
  connections/src/app/core/services/qr-code-generator.service.ts
  connections/src/app/features-michael/com-one/com-one.component.spec.ts
  connections/src/app/features-michael/com-two/com-two.component.spec.ts
  connections/src/app/features/features.module.ts
  connections/src/app/features/manage-alias/manage-alias.component.spec.ts
  connections/src/app/features/qr-code-generator/qr-code-generator.component.css
  connections/src/app/features/qr-code-generator/qr-code-generator.component.html
  connections/src/app/features/qr-code-generator/qr-code-generator.component.spec.ts
  connections/src/app/features/qr-code-generator/qr-code-generator.component.ts
  connections/src/app/features/qrcode-generate/qrcode-generate.component.html
  connections/src/app/features/qrcode-generate/qrcode-generate.component.spec.ts
  connections/src/app/features/qrcode-generate/qrcode-generate.component.ts
  package-lock.json
Labels: enhancement, don't merge, WIP

#25 s1-sid-generate-qrcode-for-panaelist-POC
  connections/src/app/app-routing.module.ts
  connections/src/app/app.module.ts
  connections/src/app/event-management/event-manager/event-manager.component.css
  connections/src/app/event-management/event-manager/event-manager.component.html
  connections/src/app/event-management/event-manager/event-manager.component.spec.ts
  connections/src/app/event-management/event-manager/event-manager.component.ts
  connections/src/app/event-management/org-sample.ts
  connections/src/app/event-management/organization-manager/organization-manager.component.css
  connections/src/app/event-management/organization-manager/organization-manager.component.html
  connections/src/app/event-management/organization-manager/organization-manager.component.spec.ts
  connections/src/app/event-management/organization-manager/organization-manager.component.ts
  connections/src/app/event-management/panelist-manager/panelist-manager.component.css
  connections/src/app/event-management/panelist-manager/panelist-manager.component.html
  connections/src/app/event-management/panelist-manager/panelist-manager.component.spec.ts
  connections/src/app/event-management/panelist-manager/panelist-manager.component.ts
  connections/src/app/features/features.module.ts
  connections/src/app/features/qr-code-generator/qr-code-generator.component.html
Labels: enhancement, don't merge, WIP

#26 messages for Sid and stubs for Emily,
  connections/src/app/app-routing.module.ts
  connections/src/app/event-management/event-manager/event-manager.component.ts
  connections/src/app/event-management/organization-manager/organization-manager.component.ts
  connections/src/app/event-management/panelist-manager/panelist-manager.component.ts
  connections/src/app/features-michael/features-michael.module.ts
  connections/src/app/features-michael/profile-display/profile-display.component.css
  connections/src/app/features-michael/profile-display/profile-display.component.html
  connections/src/app/features-michael/profile-display/profile-display.component.spec.ts
  connections/src/app/features-michael/profile-display/profile-display.component.ts
  connections/src/app/features-michael/profile-loader/profile-loader.component.css
  connections/src/app/features-michael/profile-loader/profile-loader.component.html
  connections/src/app/features-michael/profile-loader/profile-loader.component.spec.ts
  connections/src/app/features-michael/profile-loader/profile-loader.component.ts
  connections/src/app/features-michael/qr-reader/qr-reader.component.css
  connections/src/app/features-michael/qr-reader/qr-reader.component.html
  connections/src/app/features-michael/qr-reader/qr-reader.component.spec.ts
  connections/src/app/features-michael/qr-reader/qr-reader.component.ts
  connections/src/app/features/crud/crud.component.html
  connections/src/app/features/crud/crud.component.spec.ts
  connections/src/app/features/crud/crud.component.ts
  connections/src/app/features/qr-code-generator/qr-code-generator.component.html
  connections/src/app/features/qr-code-generator/qr-code-generator.component.ts
  connections/src/app/shared/pii/create-pii/create-pii.component.ts
Labels: enhancement

#29 S1 sid qr save image retrieve
  README.md
  connections/package.json
  connections/src/app/app-routing.module.ts
  connections/src/app/app.module.ts
  connections/src/app/qr-save-mock/qr-code-display/qr-code-display.component.css
  connections/src/app/qr-save-mock/qr-code-display/qr-code-display.component.html
  connections/src/app/qr-save-mock/qr-code-display/qr-code-display.component.spec.ts
  connections/src/app/qr-save-mock/qr-code-display/qr-code-display.component.ts
  connections/src/app/qr-save-mock/qr-code-save/qr-code-save.component.css
  connections/src/app/qr-save-mock/qr-code-save/qr-code-save.component.html
  connections/src/app/qr-save-mock/qr-code-save/qr-code-save.component.spec.ts
  connections/src/app/qr-save-mock/qr-code-save/qr-code-save.component.ts
  package-lock.json
  server/app.js
  server/package.json
  server/qr-codes.json
Labels: enhancement

#30 Refining profile loader
  connections/src/app/core/core.module.ts
  connections/src/app/core/models/user.interface.ts
  connections/src/app/core/pipes/initials.pipe.spec.ts
  connections/src/app/core/pipes/initials.pipe.ts
  connections/src/app/core/services/user.service.ts
  connections/src/app/features-michael/profile-loader/profile-loader.component.html
  connections/src/app/features-michael/profile-loader/profile-loader.component.ts
Labels: enhancement

#33 upgraded packages to ignore force cmd
  connections/package.json
Labels: enhancement

#34 Move Color, Flat, and Validate Color into Correct package.json
  connections/package.json
Labels: bug

#39 Demo Theme on CRUD page
  connections/src/app/core/plugins/theme.ts
  connections/src/app/features-epris/page-blue/page-blue.component.html
  connections/src/app/features-epris/page-gray/page-gray.component.html
  connections/src/app/features-epris/page-purple/page-purple.component.html
  connections/src/app/features-epris/page-red/page-red.component.html
  connections/src/app/features/crud/crud.component.css
  connections/src/app/features/crud/crud.component.html
  connections/src/app/features/crud/crud.component.ts
  connections/src/app/features/features.module.ts
  connections/src/app/material/material.module.ts
  connections/src/index.html
  connections/tailwind.config.js
Labels: enhancement, don't merge

#40 S2 ed dailies
  connections/src/app/features-michael/features-michael.module.ts
  connections/src/app/features-michael/profile-loader/profile-loader.component.html
  connections/src/app/features-michael/profile-loader/profile-loader.component.ts
  connections/src/assets/images/social-logos/tumblr.png
Labels: enhancement

#42 S2 mg controller crud
  connections/src/app/connections/connection-landing/connection-landing.component.css
  connections/src/app/connections/connection-landing/connection-landing.component.html
  connections/src/app/connections/connection-landing/connection-landing.component.spec.ts
  connections/src/app/connections/connection-landing/connection-landing.component.ts
  connections/src/app/connections/connections.module.ts
  connections/src/app/core/models/connection.interface.ts
  connections/src/app/quest/create-badge/create-badge.component.css
  connections/src/app/quest/create-badge/create-badge.component.html
  connections/src/app/quest/create-badge/create-badge.component.spec.ts
  connections/src/app/quest/create-badge/create-badge.component.ts
  connections/src/app/quest/delete-badge/delete-badge.component.css
  connections/src/app/quest/delete-badge/delete-badge.component.html
  connections/src/app/quest/delete-badge/delete-badge.component.spec.ts
  connections/src/app/quest/delete-badge/delete-badge.component.ts
  connections/src/app/quest/get-badge/get-badge.component.css
  connections/src/app/quest/get-badge/get-badge.component.html
  connections/src/app/quest/get-badge/get-badge.component.spec.ts
  connections/src/app/quest/get-badge/get-badge.component.ts
  connections/src/app/quest/quest-landing/quest-landing.component.css
  connections/src/app/quest/quest-landing/quest-landing.component.html
  connections/src/app/quest/quest-landing/quest-landing.component.spec.ts
  connections/src/app/quest/quest-landing/quest-landing.component.ts
  connections/src/app/quest/quest.module.ts
  connections/src/app/quest/update-badge/update-badge.component.css
  connections/src/app/quest/update-badge/update-badge.component.html
  connections/src/app/quest/update-badge/update-badge.component.spec.ts
  connections/src/app/quest/update-badge/update-badge.component.ts
  server/GetOrganizations.json
  server/GetThemes.json
  server/GetUserProfiles.json
  server/UpdateUserProfile.json
  server/UpdateUserTheme.json
  server/sampleConnections.json
  server/theme-updates.json
Labels: enhancement

#43 Updating to point at API
  connections/src/app/core/services/connection.service.ts
  connections/src/app/core/services/event.service.ts
  connections/src/app/core/services/links.service.ts
  connections/src/app/core/services/organization.service.ts
  connections/src/app/core/services/pii.service.ts
  connections/src/app/core/services/roles.service.ts
  connections/src/app/core/services/tags.service.ts
  connections/src/app/core/services/user.service.ts
  connections/src/app/events/create-events/create-events.component.html
  connections/src/app/events/create-events/create-events.component.ts
  connections/src/app/features/crud/crud.component.ts
  connections/src/app/shared/pii/create-pii/create-pii.component.ts
  connections/src/app/shared/roles/create-roles/create-roles.component.html
  connections/src/app/shared/roles/create-roles/create-roles.component.ts
  connections/src/environments/environment.dev.ts
Labels: help wanted

#44 adding qrcode and html2canvas to fix warnings
  connections/angular.json
Labels: enhancement

#45 Adding badges to crud
  connections/src/app/app-routing.module.ts
  connections/src/app/core/models/badge.interface.ts
  connections/src/app/core/services/badge.service.spec.ts
  connections/src/app/core/services/badge.service.ts
  connections/src/app/features/crud/crud.component.html
  connections/src/app/features/crud/crud.component.ts
  connections/src/app/quest/badge-landing/badge-landing.component.css
  connections/src/app/quest/badge-landing/badge-landing.component.html
  connections/src/app/quest/badge-landing/badge-landing.component.spec.ts
  connections/src/app/quest/badge-landing/badge-landing.component.ts
  connections/src/app/quest/create-badge/create-badge.component.html
  connections/src/app/quest/create-badge/create-badge.component.ts
  connections/src/app/quest/get-badge/get-badge.component.html
  connections/src/app/quest/get-badge/get-badge.component.ts
  connections/src/app/quest/quest.module.ts
  connections/src/app/shared/shared.module.ts
  connections/src/environments/environment.dev.ts
Labels: enhancement

#46 S2 mg controller crud
  connections/src/app/app-routing.module.ts
  connections/src/app/features-michael/features-michael.module.ts
  connections/src/app/features-michael/profile-display/profile-display.component.css
  connections/src/app/features-michael/profile-display/profile-display.component.html
  connections/src/app/features-michael/profile-display/profile-display.component.spec.ts
  connections/src/app/features-michael/profile-display/profile-display.component.ts
  connections/src/app/features/crud/crud.component.html
  connections/src/app/features/crud/crud.component.ts
  connections/src/app/quest/quest-badges-panel/quest-badges-panel.component.html
  connections/src/assets/badges/attendLg.png
  connections/src/assets/badges/attendSm.png
  connections/src/assets/badges/attendSmInactive.png
  connections/src/assets/badges/connectLg.png
  connections/src/assets/badges/connectSm.png
  connections/src/assets/badges/connectSmInactive.png
  connections/src/assets/badges/exploreLg.png
  connections/src/assets/badges/exploreSm.png
  connections/src/assets/badges/exploreSmInactive.png
  connections/src/assets/badges/followLg.png
  connections/src/assets/badges/followSm.png
  connections/src/assets/badges/followSmInactive.png
  connections/src/assets/badges/meetLg.png
  connections/src/assets/badges/meetSm.png
  connections/src/assets/badges/meetSmInactive.png
Labels: enhancement

#47 Image uploader updates
  connections/src/app/features/image-uploader/image-uploader.component.html
  connections/src/app/features/image-uploader/image-uploader.component.ts
  server/Badges.json
Labels: enhancement

#48 Moving save qr code caption to crud
  connections/src/app/features/crud/crud.component.html
  connections/src/app/features/crud/crud.component.ts
  connections/src/app/features/qr-code-generator/qr-code-generator.component.html
  connections/src/app/qr-save-mock/qr-code-save/qr-code-save.component.html
  connections/src/app/qr-save-mock/qr-code-save/qr-code-save.component.ts
Labels: enhancement

#51 Size configuration caption qrcode
  connections/src/app/qr-save-mock/qr-code-display/qr-code-display.component.html
  connections/src/app/qr-save-mock/qr-code-save/qr-code-save.component.html
  connections/src/app/qr-save-mock/qr-code-save/qr-code-save.component.ts
Labels: enhancement

#52 Custom url on scan of qr code
  connections/src/app/qr-save-mock/qr-code-save/qr-code-save.component.html
  connections/src/app/qr-save-mock/qr-code-save/qr-code-save.component.ts
Labels: enhancement
